[package]
name = "vandermonde_search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isa-l = "0.2"
bit-vec = "0.6.3"
num-bigint = "0.4.3"
rayon = "1.7.0"
